/* eslint-disable @typescript-eslint/no-unused-vars */
import './global.css';
import { BaseStyles } from '@primer/react';
import { ColorModeWithAuto } from '@primer/react/lib-esm/ThemeProvider';
import { StyledComponentsRegistry } from '../lib/registry';
import Layout from '@/components/layout';
import { ThemeProvider } from '@/lib/theme';

const colorMode: ColorModeWithAuto = 'light';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Note: the focus-visible polyfill adds additional attributes to `html`
    // that cause hydration mismatch errors
    <html
      lang="en"
      suppressHydrationWarning
      data-color-mode={colorMode}
      data-light-theme="light"
      data-dark-theme="dark"
    >
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider colorMode={colorMode}>
            <BaseStyles>
              <Layout>{children}</Layout>
            </BaseStyles>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
