import Head from 'next/head';
import { Heading } from '@primer/react';
import Link from '@/components/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading as="h1">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Heading>
        <p>
          Get started by editing
          <code>pages/index.tsx</code>
        </p>
        <Link href="/about">About</Link>
      </main>
    </>
  );
}
