import Head from 'next/head';
import Image from 'next/image'
import Link from '@/components/link';
import Avatar from '@/components/avatar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        Get started by editing
        <code>pages/index.tsx</code>
      </p>
      <Link href="/about">About</Link>
    </>
  );
}
